services:
  watermarker-dev:
    image: watermarker-dev
    build:
      context: .
      target: watermarker-dev
      platforms:
        #- linux/amd64
        - linux/arm64
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    tty: true
